spring.application.name=Socialize-Logs

spring.jackson.time-zone=Asia/Kolkata
server.port=${PORT:7863}

spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DATABASE:socialize}

auth.service.url=${AUTH_SERVICE_URL:http://localhost:7860}
user.service.url=${USER_SERVICE_URL:http://localhost:7861}
bot.service.url=${BOT_SERVICE_URL:http://localhost:7862}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
