spring.application.name=Socialize-Logs

spring.jackson.time-zone=Asia/Kolkata
server.port=7863

spring.data.mongodb.uri=mongodb+srv://chetanraowork_db_user:rECjsNNNg1b89xRT@users.jo1cfwg.mongodb.net/?appName=Users
spring.data.mongodb.database=socialize

auth.service.url=http://localhost:7860
user.service.url=http://localhost:7861
bot.service.url=http://localhost:7862

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always